### PR TITLE
Travis: use jruby-9.1.13.0

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR updates the CI matrix to use latest JRuby.

http://jruby.org/2017/09/06/jruby-9-1-13-0.html

And passes lint.

### CODE REVIEW

**Comment by shotat** [comment]
+1

**Comment by olleolleolle** [comment]
Hehe, I'll be updating to 9.1.9.0.

**Comment by olleolleolle** [comment]
...and 9.1.12.0.

**Comment by Jesterovskiy** [comment]
@olleolleolle thank you for update =)

**Pull request merged**
