### PR TITLE
Set minimum config for rubocop to show no offenses

### PR DESCRIPTION
**Pull request by jpawlyn**

### CODE REVIEW

**Comment by Jesterovskiy** [comment]
@roidrage need your attention =)

**Comment by roidrage** [comment]
@jpawlyn Thank you for the contribution! It looks like the second commit broke the tests. I don't know RubuCop myself enough to adjust either the code or the configuration. Is that something you could look into so we can get this merged?

**Comment by jpawlyn** [comment]
@roidrage Hi. The commit [Set minimum config for rubocop to show no offenses](https://github.com/roidrage/redis-session-store/pull/92/commits/9e077d43ed8d29a7e6a10f233c0c1a94fd0582f1) originally broke the tests due to a rubocop issue with version 0.49.1. The second commit is a work around for this bug. Or is there another failure that is occurring not shown above?

**Comment by roidrage** [comment]
@jpawlyn Apologies, my bad, I looked at them in the wrong order.

**Comment by roidrage** [comment]
@jpawlyn Thank you for your contribution!

**Pull request merged**
