### PR TITLE
Support options with string keys

### PR DESCRIPTION
**Pull request by daniel-g**
I load session options in a YAML, so I need to accept strings also as keys.

### CODE REVIEW

**Comment by meatballhat** [comment]
Hey @daniel-g, sorry for the long delay 😸.  Can you accomplish this at the level *just outside* of passing the loaded hash to the session config?  Adding an ActiveSupport dependency is non-trivial, imho.

**Comment by daniel-g** [comment]
@meatballhat is this still valid to merge?

**Comment by meatballhat** [comment]
@daniel-g ahoy!  Thank you for backing out the ActiveSupport dependency.  I understand the convenience of having this library handle hash key symbolizing, but I still prefer that you do this prior to passing arguments.

**Comment by daniel-g** [comment]
Yeah, I understood that when I reviewed it again :)

**Comment by daniel-g** [comment]
Closed in favor of #102

**Pull request closed without merging**
