### PR TITLE
Update Actionpack version to include all patches for 5.1

### PR DESCRIPTION
**Pull request by Jesterovskiy**

### CODE REVIEW

**Comment by Jesterovskiy** [comment]
@meatballhat Do I need fix RuboCop issues? Because he broken build.

**Comment by jpawlyn** [comment]
@Jesterovskiy FYI I've added a PR to fix the RuboCop issues https://github.com/roidrage/redis-session-store/pull/92

**Comment by jpawlyn** [comment]
@Jesterovskiy The PR to fix RuboCop issues has been merged so hopefully if you rebase against master, this PR should be green 🤞 🙇

**Comment by Jesterovskiy** [comment]
@jpawlyn Done!

**Comment by Jesterovskiy** [comment]
@roidrage your turn =)

**Comment by nimashariatian** [comment]
awesome, can this be merged and make a new release?

**Comment by nicubucalaete** [comment]
I also need these changes in order to migrate a project to Rails 5.1

**Comment by nimashariatian** [comment]
@jpawlyn can you check out this PR please? :)

**Comment by jpawlyn** [comment]
@nimashariatian I think we probably want one of the gem owners to take a look. They can hopefully merge the PR and release a new version. If you have a moment please... @meatballhat @dplummer @iancanderson 😃

**Comment by nimashariatian** [comment]
oh thanks for the update @jpawlyn !

**Comment by samcday** [comment]
Bump! We need a new release of `redis-session-store` so we can move to Rails 5.1 please :)

**Comment by nimashariatian** [comment]
yes and then we can all party? lol

**Comment by attenzione** [comment]
seems it's not going to work, because i'm getting error:

```
Gem Load Error is: uninitialized constant Rack::Session::Abstract::ENV_SESSION_OPTIONS_KEY
Backtrace for gem load error is:
/lib/redis-session-store.rb:10:in `<class:RedisSessionStore>'
```

**Comment by nimashariatian** [comment]
that's because this PR hasn't been merged yet @attenzione. you can point your gem to this PR like so: 
`gem 'redis-session-store', git: "https://github.com/CapCap/redis-session-store"`

**Comment by attenzione** [comment]
this PR will not fix issue with `Rack::Session::Abstract::ENV_SESSION_OPTIONS_KEY`, see Files changed. 

`CapCap/redis-session-store` is another fork with fix, but this PR is another

**Comment by nimashariatian** [comment]
oh you're right, was looking at the wrong PR

**Comment by samcday** [comment]
Hey @Jesterovskiy thanks for getting this PR up and then merging it. Will a new release of them gem to Rubygems.org be coming soon?

**Comment by Jesterovskiy** [comment]
@samcday I don't have rights to release on rubygems. @roidrage can you help with this?

**Pull request merged**
